type: object
properties:
  id: string
  name: string
  image:
    type: object
    properties:
      objectId: string
      uri: string
  createdAt: datetime
  subtitle?: string
  currentlyRunning: boolean
  candidateFor?: string
  officialCampaignWebsiteUri?: string
  facebookPageUri?: string
  twitterUri?: string
  googlePlusUri?: string
  language: string
